### ISSUE TITLE
Friends , Followers and Following

### ISSUE THREAD

**Issue by makensonlamour** [makensonlamour/vwanu#511]
<img width="1680" alt="Screen Shot 2022-10-14 at 10 23 07 PM" src="https://user-images.githubusercontent.com/97195529/195964684-4d008f94-6767-4b68-8509-93f68ba749da.png">
<img width="1680" alt="Screen Shot 2022-10-14 at 10 23 59 PM" src="https://user-images.githubusercontent.com/97195529/195964685-c4ab213a-8d99-4970-9fc4-e6d0fedc3c07.png">

**Comment by Wadprog** [comment]
@gh4m21 Please provide the link you use to call the API for the current login user profile

**Comment by gh4m21** [comment]
@Wadprog  Go to this file authContext using this link https://github.com/makensonlamour/vwanu/blob/dev/feathers/client/src/context/AuthContext.js and check the line 34

**Comment by Wadprog** [comment]
so it is not calling the /users endpoint at all. Therefore, I guess there is no amount of friends fields at all, right?

**Comment by gh4m21** [comment]
No. I guess there's no field for amounOfFollower and amountOfFollowing as well because they work very well

**Comment by Wadprog** [comment]
The issue has been fixed thank you @gh4m21
