### ISSUE TITLE
new issue from meeting 26/12

### ISSUE THREAD

**Issue by gh4m21** [makensonlamour/vwanu#580]
- [ ]  non-members can't see [ ] fix posts from the community @Wadprog 
- [ ] if the user didn't have a connection with one of the two users for the post on the wall, he shouldn't see the post on the timeline @Wadprog 
- [ ]  remove notification on newsfeed @gh4m21

**Comment by Wadprog** [comment]
On if user have no connection to post maker it should not see a post. Kindly not that users can see all piblic posts as requested by @makensonlamour . User are not able to see network and personal post if not paert of someone network
